class SkuList{
  static List<String> skuIslamList = [
    //Penggalang Ramu
    "Selalu taat menjalankan ibadah agamannya secara pribadi ataupun berjamaah",
    "Dapat mengetahui dan menjelaskan hari-hari besar agama di Indonesia",
    "Dapat menyebutkan agama-agama yang ada di Indonesia serta nama tempat ibadahnya",
    //Breakpoint agama
      "Dapat melakukan mandi wajib dan mengerti penyebabnya",
      "Dapat melakukan sholat berjama'ah",
      "Hafal 5 macam doa harian dan 5 macam surat-surat pendek",
    "Dapat menjelaskan tentang emosi",
    "Dapat menyampaikan pendapat dengan baik dalam suatu pertemuan Pasukan Penggalang",
    "Dapat mengetahui dan menjelaskan manfaat dari penghijauan",
    "Dapat mengetahui dan memahami tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Perkemahan Penggalang sedikitnya 2 hari, sesuai dengan standar perkemahan",
    "Dapat menyebutkan tanda-tanda pengenal Gerakan Pramuka sesuai dengan golongan dan tingkatannya",
    "Mengetahui nama Ketua RT hingga Lurah, Camat, dan tokoh masyarakat atau setingkatnya di tempat tinggalnya",
    "Dapat mengetahui dan menyebutkan Kode Kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan Pasukan Penggalang sekurang-kurangnya 8 kali latihan berturut-turut",
    "Tahu tentang : Salam Pramuka, Motto, dan Arti Lambang Gerakan Pramuka",
    "Dapat menjelaskan sejarah dan kiasan warna serta cara menggunakan bendera merah putih",
    "Dapat menjelaskan dan menyajikan lagu kebangsaan Indonesia Raya dengan sikap yang benar serta dapat menyanyikan 2 lagu wajib Nasional dan 1 lagu daerah nusantara",
    "Dapat menjelaskan tentang lambang Negara RI",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar",
    "Telah menabung secara rutin dan setia membayar uang iuran untuk regunya yang diperoleh dari usahanya sendiri",
    "Dapat menyebutkan dan menjelaskan manfaat sedikitnya 2 jenis alat teknologi informasi modern",
    "Dapat mengenal dan memilah sampah",
    "Dapat menjelaskan teknik penjernihan air",
    "Dapat membuat dan menggunakan simpul mati, simpul hidup, simpul anyam, simpul tiang, simpul pangkal dan dapat menyusuk tali, membuat ikatan serta menyambung dua tongkat",
    "Dapat menjelaskan kompas, menaksir tinggi dan lebar",
    "Mengenal macam-macam sandi, isyarat morse, dan semaphore",
    "Selalu berpakaian rapih, memelihara kesehatan dan kebersihan diri serta lingkungnnya",
    "Dapat baris-berbaris",
    "Dapat menjelaskan sedikitnya 3 cabang olahraga dan dapat melakukan 2 jenis cabang olahraga, salah satunya: olahraga renang",
    "Mengetahui adanya perbedaan perkembangan fisik tubuh",
    "Selalu melakukan aktivitas fisik tiap hari sedikitnya 30 menit",
    //Penggalang Rakit
    "Mengikuti acara-acara keagamaan sesuai dengan agamanya",
    "Membuat laporan singkat kegiatan keagamaan yang diikutinya",
    "Dapat menjelaskan bentuk toleransi beragama antar umat beragama di lingkungannya",
    //Breakpoint agama
      "Dapat menyebutkan, membaca dan menghafalkan serta memimpin 8 doa harian secara baik dan benar di hadapan regunya",
      "Dapat menceritakan sejarah Nabi Muhammad SAW",
      "Selalu melaksanakan Shalat wajib dan Sholat Jum'at bagi putera",
    "Dapat melaksanakan dan memimpin diskusi regu",
    "Menyebutkan ciri-ciri pengendalian emosi diri",
    "Melakukan kegiatan penghijauan di lingkungannya atau di daerah lainnya serta telah menanam dan merawat tanaman penghijauan",
    "Dapat menjelaskan tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Lomba Tingkat dan lomba-lomba Pramuka Penggalang, di gugus depan dan kwartir",
    "Dapat menyebutkan tanda-tanda pengenal pada pakaian seragam",
    "Dapat membuat struktur pemerintahan dari tingkat kelurahan hingga RT di tempat tinggalnya",
    "Dapat menjelaskan nilai-nilai yang terkandung dalam Satya dan Darma Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 10 kali latihan berturut-turut",
    "Dapat menjelaskan dan melaksanakan cara memberi salam pramuka",
    "Dapat menjelaskan sejarah bendera merah putih dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan sejarah Lagu Kebangsaan Indonesia Raya dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan lambang Negara dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Selalu berbicara dengan menggunakan bahasa Indonesia yang baik dan benar. Dapat membuat laporan secara tertulis dari hasil pertemuan yang diikutinya",
    "Memiliki tabungan atas nama pribadi. Aktif menabung secara rutin dengan menunjukkan keaktifannya menabung di regunya",
    "Dapat mengoperasikan dan merawat salah satu teknologi informasi",
    "Dapat mengolah sampah serta mempraktikkan cara pengolahannya secara composting",
    "Dapat melakukan proses penjernihan air secara sederhana",
    "Dapat membuat beberapa jenis pioneering, seperti: rak piring, meja makan, tiang jemuran, menara kaki tiga",
    "Dapat menggunakan kompas dan membuat peta pita, menaksir kecepatan arus dan kedalaman",
    "Dapat membuat dan menerjemahkan sandi, menerima berita dengan menggunakan bahasa morse dan semaphore",
    "Selalu berpakaian rapih di setiap saat dan memelihara kesehatan dan kebersihan diri di lingkungannya",
    "Dapat memimpin regunya untuk baris-berbaris",
    "Tahu peraturan permainan 3 cabang olahraga yang dipilihnya dan dapat melakukan salah satu yang dipilihnya",
    "Mengetahui ciri-ciri perubahan bentuk fisik tubuh pada dirinya dan paham akan norma-norma pergaulan",
    "Dapat menunjukkan jadwal kegiatan fisik dan gerakan tubuh yang dilakukan setiap hari",
    //Penggalang Terap
    "Taat menjalankan ibadah sesuai agamanya dan mengajak orang lain untuk beribadah",
    "Berperan aktif dalam penyelenggaraan kegiatan keagamaan baik dalam Gerakan Pramuka maupun di masyarakat",
    "Dapat mengajak teman/orang lain untuk berperilaku toleran antar umat beragama",
    //Breakpoint agama
      "Dapat bertindak sebagai Imam dalam sholat berjamaah di perkemahan",
      "Dapat menghafal 10 macam doa harian dan hafal 10 macam surat pendek",
      "Dapat memimpin doa",
      "Selalu melaksanakan Shalat berjamaah di Masjid/Mushola",
    "Dapat mengendalikan emosi teman sebayanya",
    "Dapat memimpin pertemuan Pasukan Penggalang",
    "Mengajak teman sebaya/regunya untuk melakukan kegiatan penghijauan dan memelihara di lingkungannya atau di daerah lain",
    "Dapat mensosialisasikan kepada teman sebaya tentang hak perlindungan anak",
    "Telah ikut serta dalam kegiatan Jambore/Lomba Tingkat/perkemahan lainnnya",
    "Dapat menjelaskan tanda-tanda pengenal Gerakan Pramuka",
    "Dapat menjelaskan tugas dan fungsi seorang Kepala Desa/Lurah, Camat, Bupati/Walikota",
    "Dapat mengajak anggota regu dan pasukannya untuk senantiasa mengamalkan kode kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 12 kali latihan berturut-turut",
    "Dapat menjelaskan dan menggunakan Salam Pramuka",
    "Dapat mengibarkan dan menurunkan bendera sang merah putih pada upacara hari-hari besar nasional atau sejenisnya",
    "Dapat memimpin lagu Indonesia Raya di depan orang lain pada suatu upacara. Dapat menyanyikan 4 lagu wajib, 3 lagu daerah tempat tinggalnya dan 3 macam lagu daerah lainnya",
    "Dapat menjelaskan Lambang Negara Republik Indonesia di depan pasukan atau teman sebayanya",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar dalam pertemuan resmi",
    "Dapat menjelaskan kepada anggota regunya/pasukannya manfaat menabung dan membayar uang iuran serta mengajak untuk melakukan gemar menabung",
    "Dapat mengajarkan penggunaan teknologi informasi kepada sedikitnya 2 jenis kepada teman sebaya",
    "Ikut mensosialisasikan cara pengolahan sampah",
    "Dapat mensosialisasikan cara penjernihan air",
    "Dapat membuat pioneering: Jembatan sederhana, Menara pandang sederhana",
    "Dapat membuat peta perjalanan, peta lapangan, menjelaskan rumus menaksir tinggi, lebar, kecepatan dan kedalaman",
    "Dapat menerima dan mengirim berita dengan menggunakan bendera morse dan semaphore serta dapat membuat sandi hasil kreasi pribadi lengkap dengan kuncinya",
    "Selalu berpakaian rapih di setiap saat dan menjadi contoh bagi teman-temannya untuk memelihara kesehatan serta kebersihan diri di lingkungannya",
    "Dapat memimpin dan melatih baris-berbaris di pasukannya",
    "Dapat melaksanakan olahraga beregu dan melakukan 3 jenis cabang olahraga serta tahu peraturannya (Salah satunya olahraga renang)",
    "Dapat mengatasi adanya perubahan perkembangan fisik tubuh",
    "Dapat menjelaskan manfaat dan melakukan aktivitas fisik tiap hari sedikitnya 45 menit"
  ];

  static List<String> skuKatolikList = [
    //Penggalang Ramu
    "Selalu taat menjalankan ibadah agamannya secara pribadi ataupun berjamaah",
    "Dapat mengetahui dan menjelaskan hari-hari besar agama di Indonesia",
    "Dapat menyebutkan agama-agama yang ada di Indonesia serta nama tempat ibadahnya",
    //Breakpoint agama
      "Dapat berdoa Rosario, dan tahu artinya",
      "Mengikuti Perayaan Ekaristi hari Minggu dan menjadi putera/puteri altar",
      "Dapat menyanyikan 3 macam lagu Gereja",
    "Dapat menjelaskan tentang emosi",
    "Dapat menyampaikan pendapat dengan baik dalam suatu pertemuan Pasukan Penggalang",
    "Dapat mengetahui dan menjelaskan manfaat dari penghijauan",
    "Dapat mengetahui dan memahami tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Perkemahan Penggalang sedikitnya 2 hari, sesuai dengan standar perkemahan",
    "Dapat menyebutkan tanda-tanda pengenal Gerakan Pramuka sesuai dengan golongan dan tingkatannya",
    "Mengetahui nama Ketua RT hingga Lurah, Camat, dan tokoh masyarakat atau setingkatnya di tempat tinggalnya",
    "Dapat mengetahui dan menyebutkan Kode Kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan Pasukan Penggalang sekurang-kurangnya 8 kali latihan berturut-turut",
    "Tahu tentang : Salam Pramuka, Motto, dan Arti Lambang Gerakan Pramuka",
    "Dapat menjelaskan sejarah dan kiasan warna serta cara menggunakan bendera merah putih",
    "Dapat menjelaskan dan menyajikan lagu kebangsaan Indonesia Raya dengan sikap yang benar serta dapat menyanyikan 2 lagu wajib Nasional dan 1 lagu daerah nusantara",
    "Dapat menjelaskan tentang lambang Negara RI",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar",
    "Telah menabung secara rutin dan setia membayar uang iuran untuk regunya yang diperoleh dari usahanya sendiri",
    "Dapat menyebutkan dan menjelaskan manfaat sedikitnya 2 jenis alat teknologi informasi modern",
    "Dapat mengenal dan memilah sampah",
    "Dapat menjelaskan teknik penjernihan air",
    "Dapat membuat dan menggunakan simpul mati, simpul hidup, simpul anyam, simpul tiang, simpul pangkal dan dapat menyusuk tali, membuat ikatan serta menyambung dua tongkat",
    "Dapat menjelaskan kompas, menaksir tinggi dan lebar",
    "Mengenal macam-macam sandi, isyarat morse, dan semaphore",
    "Selalu berpakaian rapih, memelihara kesehatan dan kebersihan diri serta lingkungnnya",
    "Dapat baris-berbaris",
    "Dapat menjelaskan sedikitnya 3 cabang olahraga dan dapat melakukan 2 jenis cabang olahraga, salah satunya: olahraga renang",
    "Mengetahui adanya perbedaan perkembangan fisik tubuh",
    "Selalu melakukan aktivitas fisik tiap hari sedikitnya 30 menit",
    //Penggalang Rakit
    "Mengikuti acara-acara keagamaan sesuai dengan agamanya",
    "Membuat laporan singkat kegiatan keagamaan yang diikutinya",
    "Dapat menjelaskan bentuk toleransi beragama antar umat beragama di lingkungannya",
    //Breakpoint agama
      "Mengetahui siapa Kristus",
      "Dapat berdoa dengan kata-katanya sendiri",
      "Dapat menyanyikan lagu-lagu Gereja",
    "Dapat melaksanakan dan memimpin diskusi regu",
    "Menyebutkan ciri-ciri pengendalian emosi diri",
    "Melakukan kegiatan penghijauan di lingkungannya atau di daerah lainnya serta telah menanam dan merawat tanaman penghijauan",
    "Dapat menjelaskan tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Lomba Tingkat dan lomba-lomba Pramuka Penggalang, di gugus depan dan kwartir",
    "Dapat menyebutkan tanda-tanda pengenal pada pakaian seragam",
    "Dapat membuat struktur pemerintahan dari tingkat kelurahan hingga RT di tempat tinggalnya",
    "Dapat menjelaskan nilai-nilai yang terkandung dalam Satya dan Darma Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 10 kali latihan berturut-turut",
    "Dapat menjelaskan dan melaksanakan cara memberi salam pramuka",
    "Dapat menjelaskan sejarah bendera merah putih dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan sejarah Lagu Kebangsaan Indonesia Raya dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan lambang Negara dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Selalu berbicara dengan menggunakan bahasa Indonesia yang baik dan benar. Dapat membuat laporan secara tertulis dari hasil pertemuan yang diikutinya",
    "Memiliki tabungan atas nama pribadi. Aktif menabung secara rutin dengan menunjukkan keaktifannya menabung di regunya",
    "Dapat mengoperasikan dan merawat salah satu teknologi informasi",
    "Dapat mengolah sampah serta mempraktikkan cara pengolahannya secara composting",
    "Dapat melakukan proses penjernihan air secara sederhana",
    "Dapat membuat beberapa jenis pioneering, seperti: rak piring, meja makan, tiang jemuran, menara kaki tiga",
    "Dapat menggunakan kompas dan membuat peta pita, menaksir kecepatan arus dan kedalaman",
    "Dapat membuat dan menerjemahkan sandi, menerima berita dengan menggunakan bahasa morse dan semaphore",
    "Selalu berpakaian rapih di setiap saat dan memelihara kesehatan dan kebersihan diri di lingkungannya",
    "Dapat memimpin regunya untuk baris-berbaris",
    "Tahu peraturan permainan 3 cabang olahraga yang dipilihnya dan dapat melakukan salah satu yang dipilihnya",
    "Mengetahui ciri-ciri perubahan bentuk fisik tubuh pada dirinya dan paham akan norma-norma pergaulan",
    "Dapat menunjukkan jadwal kegiatan fisik dan gerakan tubuh yang dilakukan setiap hari",
    //Penggalang Terap
    "Taat menjalankan ibadah sesuai agamanya dan mengajak orang lain untuk beribadah",
    "Berperan aktif dalam penyelenggaraan kegiatan keagamaan baik dalam Gerakan Pramuka maupun di masyarakat",
    "Dapat mengajak teman/orang lain untuk berperilaku toleran antar umat beragama",
    //Breakpoint agama
      "Tahu arti Perayaan Ekaristi, dan bagian-bagian yang penting",
      "Tahu peralatan Misa dan warna-warna Liturgi",
      "Tahu hierarki Gereja",
    "Dapat mengendalikan emosi teman sebayanya",
    "Dapat memimpin pertemuan Pasukan Penggalang",
    "Mengajak teman sebaya/regunya untuk melakukan kegiatan penghijauan dan memelihara di lingkungannya atau di daerah lain",
    "Dapat mensosialisasikan kepada teman sebaya tentang hak perlindungan anak",
    "Telah ikut serta dalam kegiatan Jambore/Lomba Tingkat/perkemahan lainnnya",
    "Dapat menjelaskan tanda-tanda pengenal Gerakan Pramuka",
    "Dapat menjelaskan tugas dan fungsi seorang Kepala Desa/Lurah, Camat, Bupati/Walikota",
    "Dapat mengajak anggota regu dan pasukannya untuk senantiasa mengamalkan kode kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 12 kali latihan berturut-turut",
    "Dapat menjelaskan dan menggunakan Salam Pramuka",
    "Dapat mengibarkan dan menurunkan bendera sang merah putih pada upacara hari-hari besar nasional atau sejenisnya",
    "Dapat memimpin lagu Indonesia Raya di depan orang lain pada suatu upacara. Dapat menyanyikan 4 lagu wajib, 3 lagu daerah tempat tinggalnya dan 3 macam lagu daerah lainnya",
    "Dapat menjelaskan Lambang Negara Republik Indonesia di depan pasukan atau teman sebayanya",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar dalam pertemuan resmi",
    "Dapat menjelaskan kepada anggota regunya/pasukannya manfaat menabung dan membayar uang iuran serta mengajak untuk melakukan gemar menabung",
    "Dapat mengajarkan penggunaan teknologi informasi kepada sedikitnya 2 jenis kepada teman sebaya",
    "Ikut mensosialisasikan cara pengolahan sampah",
    "Dapat mensosialisasikan cara penjernihan air",
    "Dapat membuat pioneering: Jembatan sederhana, Menara pandang sederhana",
    "Dapat membuat peta perjalanan, peta lapangan, menjelaskan rumus menaksir tinggi, lebar, kecepatan dan kedalaman",
    "Dapat menerima dan mengirim berita dengan menggunakan bendera morse dan semaphore serta dapat membuat sandi hasil kreasi pribadi lengkap dengan kuncinya",
    "Selalu berpakaian rapih di setiap saat dan menjadi contoh bagi teman-temannya untuk memelihara kesehatan serta kebersihan diri di lingkungannya",
    "Dapat memimpin dan melatih baris-berbaris di pasukannya",
    "Dapat melaksanakan olahraga beregu dan melakukan 3 jenis cabang olahraga serta tahu peraturannya (Salah satunya olahraga renang)",
    "Dapat mengatasi adanya perubahan perkembangan fisik tubuh",
    "Dapat menjelaskan manfaat dan melakukan aktivitas fisik tiap hari sedikitnya 45 menit",
  ];

  static List<String> skuKristenList = [
    //Penggalang Ramu
    "Selalu taat menjalankan ibadah agamannya secara pribadi ataupun berjamaah",
    "Dapat mengetahui dan menjelaskan hari-hari besar agama di Indonesia",
    "Dapat menyebutkan agama-agama yang ada di Indonesia serta nama tempat ibadahnya",
    //Breakpoint agama
      "Dapat menyanyikan beberapa nyanyian Gereja",
      "Dapat menceritakan 2 hikayat dari Alkitab",
      "Dapat melakukan doa sederhana pada kesempatan tertentu",
      "Dapat menyebutkan hari-hari Raya Kristiani",
    "Dapat menjelaskan tentang emosi",
    "Dapat menyampaikan pendapat dengan baik dalam suatu pertemuan Pasukan Penggalang",
    "Dapat mengetahui dan menjelaskan manfaat dari penghijauan",
    "Dapat mengetahui dan memahami tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Perkemahan Penggalang sedikitnya 2 hari, sesuai dengan standar perkemahan",
    "Dapat menyebutkan tanda-tanda pengenal Gerakan Pramuka sesuai dengan golongan dan tingkatannya",
    "Mengetahui nama Ketua RT hingga Lurah, Camat, dan tokoh masyarakat atau setingkatnya di tempat tinggalnya",
    "Dapat mengetahui dan menyebutkan Kode Kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan Pasukan Penggalang sekurang-kurangnya 8 kali latihan berturut-turut",
    "Tahu tentang : Salam Pramuka, Motto, dan Arti Lambang Gerakan Pramuka",
    "Dapat menjelaskan sejarah dan kiasan warna serta cara menggunakan bendera merah putih",
    "Dapat menjelaskan dan menyajikan lagu kebangsaan Indonesia Raya dengan sikap yang benar serta dapat menyanyikan 2 lagu wajib Nasional dan 1 lagu daerah nusantara",
    "Dapat menjelaskan tentang lambang Negara RI",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar",
    "Telah menabung secara rutin dan setia membayar uang iuran untuk regunya yang diperoleh dari usahanya sendiri",
    "Dapat menyebutkan dan menjelaskan manfaat sedikitnya 2 jenis alat teknologi informasi modern",
    "Dapat mengenal dan memilah sampah",
    "Dapat menjelaskan teknik penjernihan air",
    "Dapat membuat dan menggunakan simpul mati, simpul hidup, simpul anyam, simpul tiang, simpul pangkal dan dapat menyusuk tali, membuat ikatan serta menyambung dua tongkat",
    "Dapat menjelaskan kompas, menaksir tinggi dan lebar",
    "Mengenal macam-macam sandi, isyarat morse, dan semaphore",
    "Selalu berpakaian rapih, memelihara kesehatan dan kebersihan diri serta lingkungnnya",
    "Dapat baris-berbaris",
    "Dapat menjelaskan sedikitnya 3 cabang olahraga dan dapat melakukan 2 jenis cabang olahraga, salah satunya: olahraga renang",
    "Mengetahui adanya perbedaan perkembangan fisik tubuh",
    "Selalu melakukan aktivitas fisik tiap hari sedikitnya 30 menit",
    //Penggalang Rakit
    "Mengikuti acara-acara keagamaan sesuai dengan agamanya",
    "Membuat laporan singkat kegiatan keagamaan yang diikutinya",
    "Dapat menjelaskan bentuk toleransi beragama antar umat beragama di lingkungannya",
    //Breakpoint agama
      "Mengetahu makna doa",
      "Dapat menguraikan beberapa nyanyian Gereja yang dikenal",
      "Mengetahui pembagian Alkitab",
      "Dapat menguraikan secara singkat isi dari 2 buku di dalam Perjanjian Baru",
    "Dapat melaksanakan dan memimpin diskusi regu",
    "Menyebutkan ciri-ciri pengendalian emosi diri",
    "Melakukan kegiatan penghijauan di lingkungannya atau di daerah lainnya serta telah menanam dan merawat tanaman penghijauan",
    "Dapat menjelaskan tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Lomba Tingkat dan lomba-lomba Pramuka Penggalang, di gugus depan dan kwartir",
    "Dapat menyebutkan tanda-tanda pengenal pada pakaian seragam",
    "Dapat membuat struktur pemerintahan dari tingkat kelurahan hingga RT di tempat tinggalnya",
    "Dapat menjelaskan nilai-nilai yang terkandung dalam Satya dan Darma Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 10 kali latihan berturut-turut",
    "Dapat menjelaskan dan melaksanakan cara memberi salam pramuka",
    "Dapat menjelaskan sejarah bendera merah putih dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan sejarah Lagu Kebangsaan Indonesia Raya dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan lambang Negara dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Selalu berbicara dengan menggunakan bahasa Indonesia yang baik dan benar. Dapat membuat laporan secara tertulis dari hasil pertemuan yang diikutinya",
    "Memiliki tabungan atas nama pribadi. Aktif menabung secara rutin dengan menunjukkan keaktifannya menabung di regunya",
    "Dapat mengoperasikan dan merawat salah satu teknologi informasi",
    "Dapat mengolah sampah serta mempraktikkan cara pengolahannya secara composting",
    "Dapat melakukan proses penjernihan air secara sederhana",
    "Dapat membuat beberapa jenis pioneering, seperti: rak piring, meja makan, tiang jemuran, menara kaki tiga",
    "Dapat menggunakan kompas dan membuat peta pita, menaksir kecepatan arus dan kedalaman",
    "Dapat membuat dan menerjemahkan sandi, menerima berita dengan menggunakan bahasa morse dan semaphore",
    "Selalu berpakaian rapih di setiap saat dan memelihara kesehatan dan kebersihan diri di lingkungannya",
    "Dapat memimpin regunya untuk baris-berbaris",
    "Tahu peraturan permainan 3 cabang olahraga yang dipilihnya dan dapat melakukan salah satu yang dipilihnya",
    "Mengetahui ciri-ciri perubahan bentuk fisik tubuh pada dirinya dan paham akan norma-norma pergaulan",
    "Dapat menunjukkan jadwal kegiatan fisik dan gerakan tubuh yang dilakukan setiap hari",
    //Penggalang Terap
    "Taat menjalankan ibadah sesuai agamanya dan mengajak orang lain untuk beribadah",
    "Berperan aktif dalam penyelenggaraan kegiatan keagamaan baik dalam Gerakan Pramuka maupun di masyarakat",
    "Dapat mengajak teman/orang lain untuk berperilaku toleran antar umat beragama",
    //Breakpoint agama
      "Dapat memimpin beberapa nyanyian Gereja dalam pertemuan-pertemuan Penggalang",
      "Dapat memimpin doa dalam pertemua-pertemuan Penggalang",
      "Dapat menjelaskan Hukum Kasih (Lukas 10:27 dan Matius 22:37-40)",
      "Dapat menjelaskan tentang 12 pengakuan Iman Rasuli",
    "Dapat mengendalikan emosi teman sebayanya",
    "Dapat memimpin pertemuan Pasukan Penggalang",
    "Mengajak teman sebaya/regunya untuk melakukan kegiatan penghijauan dan memelihara di lingkungannya atau di daerah lain",
    "Dapat mensosialisasikan kepada teman sebaya tentang hak perlindungan anak",
    "Telah ikut serta dalam kegiatan Jambore/Lomba Tingkat/perkemahan lainnnya",
    "Dapat menjelaskan tanda-tanda pengenal Gerakan Pramuka",
    "Dapat menjelaskan tugas dan fungsi seorang Kepala Desa/Lurah, Camat, Bupati/Walikota",
    "Dapat mengajak anggota regu dan pasukannya untuk senantiasa mengamalkan kode kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 12 kali latihan berturut-turut",
    "Dapat menjelaskan dan menggunakan Salam Pramuka",
    "Dapat mengibarkan dan menurunkan bendera sang merah putih pada upacara hari-hari besar nasional atau sejenisnya",
    "Dapat memimpin lagu Indonesia Raya di depan orang lain pada suatu upacara. Dapat menyanyikan 4 lagu wajib, 3 lagu daerah tempat tinggalnya dan 3 macam lagu daerah lainnya",
    "Dapat menjelaskan Lambang Negara Republik Indonesia di depan pasukan atau teman sebayanya",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar dalam pertemuan resmi",
    "Dapat menjelaskan kepada anggota regunya/pasukannya manfaat menabung dan membayar uang iuran serta mengajak untuk melakukan gemar menabung",
    "Dapat mengajarkan penggunaan teknologi informasi kepada sedikitnya 2 jenis kepada teman sebaya",
    "Ikut mensosialisasikan cara pengolahan sampah",
    "Dapat mensosialisasikan cara penjernihan air",
    "Dapat membuat pioneering: Jembatan sederhana, Menara pandang sederhana",
    "Dapat membuat peta perjalanan, peta lapangan, menjelaskan rumus menaksir tinggi, lebar, kecepatan dan kedalaman",
    "Dapat menerima dan mengirim berita dengan menggunakan bendera morse dan semaphore serta dapat membuat sandi hasil kreasi pribadi lengkap dengan kuncinya",
    "Selalu berpakaian rapih di setiap saat dan menjadi contoh bagi teman-temannya untuk memelihara kesehatan serta kebersihan diri di lingkungannya",
    "Dapat memimpin dan melatih baris-berbaris di pasukannya",
    "Dapat melaksanakan olahraga beregu dan melakukan 3 jenis cabang olahraga serta tahu peraturannya (Salah satunya olahraga renang)",
    "Dapat mengatasi adanya perubahan perkembangan fisik tubuh",
    "Dapat menjelaskan manfaat dan melakukan aktivitas fisik tiap hari sedikitnya 45 menit",
  ];

  static List<String> skuHinduList = [
    //Penggalang Ramu
    "Selalu taat menjalankan ibadah agamannya secara pribadi ataupun berjamaah",
    "Dapat mengetahui dan menjelaskan hari-hari besar agama di Indonesia",
    "Dapat menyebutkan agama-agama yang ada di Indonesia serta nama tempat ibadahnya",
    //Breakpoint agama
      "Dapat melafalkan dan mengerti arti dari bait masing-masing mantram puja Tri Sandhya dan melaksanakannya/praktik dalam kehidupan sehari-hari",
      "Dapat menyebutkan nama-nama para Maha Rsi penerima Wahyu",
      "Dapat menyebutkan nama-nama pura dalam cakupan Sad Kahyangan",
      "Dapat menyebutkan tokoh-tokoh dalam epos cerita Mahabharata dan Ramayana",
      "Dapat menguraikan arti dan makna kata Tatwamsi",
      "Dapat menguraikan dan menjelaskan fase kehidupan dalam ajaran Catur Asrama",
      "Dapat mempraktikkan satu gerakan Yoga Asanas",
    "Dapat menjelaskan tentang emosi",
    "Dapat menyampaikan pendapat dengan baik dalam suatu pertemuan Pasukan Penggalang",
    "Dapat mengetahui dan menjelaskan manfaat dari penghijauan",
    "Dapat mengetahui dan memahami tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Perkemahan Penggalang sedikitnya 2 hari, sesuai dengan standar perkemahan",
    "Dapat menyebutkan tanda-tanda pengenal Gerakan Pramuka sesuai dengan golongan dan tingkatannya",
    "Mengetahui nama Ketua RT hingga Lurah, Camat, dan tokoh masyarakat atau setingkatnya di tempat tinggalnya",
    "Dapat mengetahui dan menyebutkan Kode Kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan Pasukan Penggalang sekurang-kurangnya 8 kali latihan berturut-turut",
    "Tahu tentang : Salam Pramuka, Motto, dan Arti Lambang Gerakan Pramuka",
    "Dapat menjelaskan sejarah dan kiasan warna serta cara menggunakan bendera merah putih",
    "Dapat menjelaskan dan menyajikan lagu kebangsaan Indonesia Raya dengan sikap yang benar serta dapat menyanyikan 2 lagu wajib Nasional dan 1 lagu daerah nusantara",
    "Dapat menjelaskan tentang lambang Negara RI",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar",
    "Telah menabung secara rutin dan setia membayar uang iuran untuk regunya yang diperoleh dari usahanya sendiri",
    "Dapat menyebutkan dan menjelaskan manfaat sedikitnya 2 jenis alat teknologi informasi modern",
    "Dapat mengenal dan memilah sampah",
    "Dapat menjelaskan teknik penjernihan air",
    "Dapat membuat dan menggunakan simpul mati, simpul hidup, simpul anyam, simpul tiang, simpul pangkal dan dapat menyusuk tali, membuat ikatan serta menyambung dua tongkat",
    "Dapat menjelaskan kompas, menaksir tinggi dan lebar",
    "Mengenal macam-macam sandi, isyarat morse, dan semaphore",
    "Selalu berpakaian rapih, memelihara kesehatan dan kebersihan diri serta lingkungnnya",
    "Dapat baris-berbaris",
    "Dapat menjelaskan sedikitnya 3 cabang olahraga dan dapat melakukan 2 jenis cabang olahraga, salah satunya: olahraga renang",
    "Mengetahui adanya perbedaan perkembangan fisik tubuh",
    "Selalu melakukan aktivitas fisik tiap hari sedikitnya 30 menit",
    //Penggalang Rakit
    "Mengikuti acara-acara keagamaan sesuai dengan agamanya",
    "Membuat laporan singkat kegiatan keagamaan yang diikutinya",
    "Dapat menjelaskan bentuk toleransi beragama antar umat beragama di lingkungannya",
    //Breakpoint agama
      "Dapat melafalkan dan memahami arti bait-bait Puja Tri Sandya serta menjalankannya dalam kehidupan sehari-hari",
      "Dapat berperan aktif dalam setiap upacara/pelaksanaan Panca Yadnya di masyarakat",
      "Dapat menyebutkan dan memahami ajaran Catur Paramita",
      "Dapat memahami dan mempraktikkan ajaran Tatwasmi seperti menerapkan sikap kasih sayang dalam kehidupan nyata, menolong mahkluk yang lemah, membantu yang terkena musibah, melestarikan suaka",
      "Mempraktikan sikap hidup suka beramal/berdana punia",
      "Dapat melafalkan dan mengkidungkan salah satu bentuk Dharma Gita",
      "Dapat mempraktikkan minimal 3 gerakan Yoga Asanas",
      "Dapat menarikan salah satu bentuk tarian sakral keagamaan Hindu (misalnya: Tari Baris, Tari Rejang, Tari Wayang Orang, dan lain-lain)",
    "Dapat melaksanakan dan memimpin diskusi regu",
    "Menyebutkan ciri-ciri pengendalian emosi diri",
    "Melakukan kegiatan penghijauan di lingkungannya atau di daerah lainnya serta telah menanam dan merawat tanaman penghijauan",
    "Dapat menjelaskan tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Lomba Tingkat dan lomba-lomba Pramuka Penggalang, di gugus depan dan kwartir",
    "Dapat menyebutkan tanda-tanda pengenal pada pakaian seragam",
    "Dapat membuat struktur pemerintahan dari tingkat kelurahan hingga RT di tempat tinggalnya",
    "Dapat menjelaskan nilai-nilai yang terkandung dalam Satya dan Darma Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 10 kali latihan berturut-turut",
    "Dapat menjelaskan dan melaksanakan cara memberi salam pramuka",
    "Dapat menjelaskan sejarah bendera merah putih dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan sejarah Lagu Kebangsaan Indonesia Raya dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan lambang Negara dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Selalu berbicara dengan menggunakan bahasa Indonesia yang baik dan benar. Dapat membuat laporan secara tertulis dari hasil pertemuan yang diikutinya",
    "Memiliki tabungan atas nama pribadi. Aktif menabung secara rutin dengan menunjukkan keaktifannya menabung di regunya",
    "Dapat mengoperasikan dan merawat salah satu teknologi informasi",
    "Dapat mengolah sampah serta mempraktikkan cara pengolahannya secara composting",
    "Dapat melakukan proses penjernihan air secara sederhana",
    "Dapat membuat beberapa jenis pioneering, seperti: rak piring, meja makan, tiang jemuran, menara kaki tiga",
    "Dapat menggunakan kompas dan membuat peta pita, menaksir kecepatan arus dan kedalaman",
    "Dapat membuat dan menerjemahkan sandi, menerima berita dengan menggunakan bahasa morse dan semaphore",
    "Selalu berpakaian rapih di setiap saat dan memelihara kesehatan dan kebersihan diri di lingkungannya",
    "Dapat memimpin regunya untuk baris-berbaris",
    "Tahu peraturan permainan 3 cabang olahraga yang dipilihnya dan dapat melakukan salah satu yang dipilihnya",
    "Mengetahui ciri-ciri perubahan bentuk fisik tubuh pada dirinya dan paham akan norma-norma pergaulan",
    "Dapat menunjukkan jadwal kegiatan fisik dan gerakan tubuh yang dilakukan setiap hari",
    //Penggalang Terap
    "Taat menjalankan ibadah sesuai agamanya dan mengajak orang lain untuk beribadah",
    "Berperan aktif dalam penyelenggaraan kegiatan keagamaan baik dalam Gerakan Pramuka maupun di masyarakat",
    "Dapat mengajak teman/orang lain untuk berperilaku toleran antar umat beragama",
    //Breakpoint agama
      "Dapat melafalkan dan memahami arti bait-bait dalam matram Puja Tri Sandya serta dapat dan mampu memimpin pelaksanaan persembahyangan",
      "Dapat menyebutkan bagian-bagian kepemimpinan Hindu dalam Asta Brata",
      "Dapat memahami serta menerapkan Ajaran Tri Hita Karana dalam kehidupan sehari-hari",
      "Dapat menjelaskan pengertian dan konsep ajaran Rwa Bhineda",
      "Dapat menguraikan dan memahami kaitan ajaran Catur asrama dan catur Purusa Artha",
      "Dapat mempraktikkan 5 gerakan Yoga Asanas",
      "Dapat menarikan lebih dari satu bentuk taruan sakral keagamaan Hindu",
      "Dapat melafalkan dan mengkidungkan salah satu bentuk Dharma Gita",
    "Dapat mengendalikan emosi teman sebayanya",
    "Dapat memimpin pertemuan Pasukan Penggalang",
    "Mengajak teman sebaya/regunya untuk melakukan kegiatan penghijauan dan memelihara di lingkungannya atau di daerah lain",
    "Dapat mensosialisasikan kepada teman sebaya tentang hak perlindungan anak",
    "Telah ikut serta dalam kegiatan Jambore/Lomba Tingkat/perkemahan lainnnya",
    "Dapat menjelaskan tanda-tanda pengenal Gerakan Pramuka",
    "Dapat menjelaskan tugas dan fungsi seorang Kepala Desa/Lurah, Camat, Bupati/Walikota",
    "Dapat mengajak anggota regu dan pasukannya untuk senantiasa mengamalkan kode kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 12 kali latihan berturut-turut",
    "Dapat menjelaskan dan menggunakan Salam Pramuka",
    "Dapat mengibarkan dan menurunkan bendera sang merah putih pada upacara hari-hari besar nasional atau sejenisnya",
    "Dapat memimpin lagu Indonesia Raya di depan orang lain pada suatu upacara. Dapat menyanyikan 4 lagu wajib, 3 lagu daerah tempat tinggalnya dan 3 macam lagu daerah lainnya",
    "Dapat menjelaskan Lambang Negara Republik Indonesia di depan pasukan atau teman sebayanya",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar dalam pertemuan resmi",
    "Dapat menjelaskan kepada anggota regunya/pasukannya manfaat menabung dan membayar uang iuran serta mengajak untuk melakukan gemar menabung",
    "Dapat mengajarkan penggunaan teknologi informasi kepada sedikitnya 2 jenis kepada teman sebaya",
    "Ikut mensosialisasikan cara pengolahan sampah",
    "Dapat mensosialisasikan cara penjernihan air",
    "Dapat membuat pioneering: Jembatan sederhana, Menara pandang sederhana",
    "Dapat membuat peta perjalanan, peta lapangan, menjelaskan rumus menaksir tinggi, lebar, kecepatan dan kedalaman",
    "Dapat menerima dan mengirim berita dengan menggunakan bendera morse dan semaphore serta dapat membuat sandi hasil kreasi pribadi lengkap dengan kuncinya",
    "Selalu berpakaian rapih di setiap saat dan menjadi contoh bagi teman-temannya untuk memelihara kesehatan serta kebersihan diri di lingkungannya",
    "Dapat memimpin dan melatih baris-berbaris di pasukannya",
    "Dapat melaksanakan olahraga beregu dan melakukan 3 jenis cabang olahraga serta tahu peraturannya (Salah satunya olahraga renang)",
    "Dapat mengatasi adanya perubahan perkembangan fisik tubuh",
    "Dapat menjelaskan manfaat dan melakukan aktivitas fisik tiap hari sedikitnya 45 menit"
  ];

  static List<String> skuBuddhaList = [
    //Penggalang Ramu
    "Selalu taat menjalankan ibadah agamannya secara pribadi ataupun berjamaah",
    "Dapat mengetahui dan menjelaskan hari-hari besar agama di Indonesia",
    "Dapat menyebutkan agama-agama yang ada di Indonesia serta nama tempat ibadahnya",
    //Breakpoint agama
      "Dapat menjelaskan arti/makna simbol yang terdapat di Altar Buddha",
      "Dapat menyanyikan lagu Pancasila Buddhis",
      "dapat melakukan dana paramita",
    "Dapat menjelaskan tentang emosi",
    "Dapat menyampaikan pendapat dengan baik dalam suatu pertemuan Pasukan Penggalang",
    "Dapat mengetahui dan menjelaskan manfaat dari penghijauan",
    "Dapat mengetahui dan memahami tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Perkemahan Penggalang sedikitnya 2 hari, sesuai dengan standar perkemahan",
    "Dapat menyebutkan tanda-tanda pengenal Gerakan Pramuka sesuai dengan golongan dan tingkatannya",
    "Mengetahui nama Ketua RT hingga Lurah, Camat, dan tokoh masyarakat atau setingkatnya di tempat tinggalnya",
    "Dapat mengetahui dan menyebutkan Kode Kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan Pasukan Penggalang sekurang-kurangnya 8 kali latihan berturut-turut",
    "Tahu tentang : Salam Pramuka, Motto, dan Arti Lambang Gerakan Pramuka",
    "Dapat menjelaskan sejarah dan kiasan warna serta cara menggunakan bendera merah putih",
    "Dapat menjelaskan dan menyajikan lagu kebangsaan Indonesia Raya dengan sikap yang benar serta dapat menyanyikan 2 lagu wajib Nasional dan 1 lagu daerah nusantara",
    "Dapat menjelaskan tentang lambang Negara RI",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar",
    "Telah menabung secara rutin dan setia membayar uang iuran untuk regunya yang diperoleh dari usahanya sendiri",
    "Dapat menyebutkan dan menjelaskan manfaat sedikitnya 2 jenis alat teknologi informasi modern",
    "Dapat mengenal dan memilah sampah",
    "Dapat menjelaskan teknik penjernihan air",
    "Dapat membuat dan menggunakan simpul mati, simpul hidup, simpul anyam, simpul tiang, simpul pangkal dan dapat menyusuk tali, membuat ikatan serta menyambung dua tongkat",
    "Dapat menjelaskan kompas, menaksir tinggi dan lebar",
    "Mengenal macam-macam sandi, isyarat morse, dan semaphore",
    "Selalu berpakaian rapih, memelihara kesehatan dan kebersihan diri serta lingkungnnya",
    "Dapat baris-berbaris",
    "Dapat menjelaskan sedikitnya 3 cabang olahraga dan dapat melakukan 2 jenis cabang olahraga, salah satunya: olahraga renang",
    "Mengetahui adanya perbedaan perkembangan fisik tubuh",
    "Selalu melakukan aktivitas fisik tiap hari sedikitnya 30 menit",
    //Penggalang Rakit
    "Mengikuti acara-acara keagamaan sesuai dengan agamanya",
    "Membuat laporan singkat kegiatan keagamaan yang diikutinya",
    "Dapat menjelaskan bentuk toleransi beragama antar umat beragama di lingkungannya",
    //Breakpoint agama
      "Dapat melakukan kebaktian baik perorangan maupun bersama-sama",
      "Dapat menyebutkan hari-hari raya Agama Buddha",
      "Dapat melakukan sikap meditasi",
      "Dapat menyanyikan lagu Aku Berlindung",
      "Dapat melakukan dana paramita",
    "Dapat melaksanakan dan memimpin diskusi regu",
    "Menyebutkan ciri-ciri pengendalian emosi diri",
    "Melakukan kegiatan penghijauan di lingkungannya atau di daerah lainnya serta telah menanam dan merawat tanaman penghijauan",
    "Dapat menjelaskan tentang hak perlindungan anak",
    "Ikut serta dalam kegiatan Lomba Tingkat dan lomba-lomba Pramuka Penggalang, di gugus depan dan kwartir",
    "Dapat menyebutkan tanda-tanda pengenal pada pakaian seragam",
    "Dapat membuat struktur pemerintahan dari tingkat kelurahan hingga RT di tempat tinggalnya",
    "Dapat menjelaskan nilai-nilai yang terkandung dalam Satya dan Darma Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 10 kali latihan berturut-turut",
    "Dapat menjelaskan dan melaksanakan cara memberi salam pramuka",
    "Dapat menjelaskan sejarah bendera merah putih dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan sejarah Lagu Kebangsaan Indonesia Raya dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Dapat menjelaskan lambang Negara dan perlakuannya (Memahami UU No.24 Tahun 2009)",
    "Selalu berbicara dengan menggunakan bahasa Indonesia yang baik dan benar. Dapat membuat laporan secara tertulis dari hasil pertemuan yang diikutinya",
    "Memiliki tabungan atas nama pribadi. Aktif menabung secara rutin dengan menunjukkan keaktifannya menabung di regunya",
    "Dapat mengoperasikan dan merawat salah satu teknologi informasi",
    "Dapat mengolah sampah serta mempraktikkan cara pengolahannya secara composting",
    "Dapat melakukan proses penjernihan air secara sederhana",
    "Dapat membuat beberapa jenis pioneering, seperti: rak piring, meja makan, tiang jemuran, menara kaki tiga",
    "Dapat menggunakan kompas dan membuat peta pita, menaksir kecepatan arus dan kedalaman",
    "Dapat membuat dan menerjemahkan sandi, menerima berita dengan menggunakan bahasa morse dan semaphore",
    "Selalu berpakaian rapih di setiap saat dan memelihara kesehatan dan kebersihan diri di lingkungannya",
    "Dapat memimpin regunya untuk baris-berbaris",
    "Tahu peraturan permainan 3 cabang olahraga yang dipilihnya dan dapat melakukan salah satu yang dipilihnya",
    "Mengetahui ciri-ciri perubahan bentuk fisik tubuh pada dirinya dan paham akan norma-norma pergaulan",
    "Dapat menunjukkan jadwal kegiatan fisik dan gerakan tubuh yang dilakukan setiap hari",
    //Penggalang Terap
    "Taat menjalankan ibadah sesuai agamanya dan mengajak orang lain untuk beribadah",
    "Berperan aktif dalam penyelenggaraan kegiatan keagamaan baik dalam Gerakan Pramuka maupun di masyarakat",
    "Dapat mengajak teman/orang lain untuk berperilaku toleran antar umat beragama",
    //Breakpoint agama
      "Dapat melakukan kebaktian baik perorangan maupun bersama-sama",
      "Dapat melakukan meditasi",
      "Dapat menyanyikan lagu Malam Suci Waisak",
      "Dapat menyebutkan tempat-tempat suci Agama Buddha",
      "Dapat menceritakan silsilah keluarga Pangeran Siddharta Gautama",
    "Dapat mengendalikan emosi teman sebayanya",
    "Dapat memimpin pertemuan Pasukan Penggalang",
    "Mengajak teman sebaya/regunya untuk melakukan kegiatan penghijauan dan memelihara di lingkungannya atau di daerah lain",
    "Dapat mensosialisasikan kepada teman sebaya tentang hak perlindungan anak",
    "Telah ikut serta dalam kegiatan Jambore/Lomba Tingkat/perkemahan lainnnya",
    "Dapat menjelaskan tanda-tanda pengenal Gerakan Pramuka",
    "Dapat menjelaskan tugas dan fungsi seorang Kepala Desa/Lurah, Camat, Bupati/Walikota",
    "Dapat mengajak anggota regu dan pasukannya untuk senantiasa mengamalkan kode kehormatan Pramuka Penggalang",
    "Rajin dan giat mengikuti latihan pasukan Penggalang sekurang-kurangnya 12 kali latihan berturut-turut",
    "Dapat menjelaskan dan menggunakan Salam Pramuka",
    "Dapat mengibarkan dan menurunkan bendera sang merah putih pada upacara hari-hari besar nasional atau sejenisnya",
    "Dapat memimpin lagu Indonesia Raya di depan orang lain pada suatu upacara. Dapat menyanyikan 4 lagu wajib, 3 lagu daerah tempat tinggalnya dan 3 macam lagu daerah lainnya",
    "Dapat menjelaskan Lambang Negara Republik Indonesia di depan pasukan atau teman sebayanya",
    "Dapat menggunakan Bahasa Indonesia yang baik dan benar dalam pertemuan resmi",
    "Dapat menjelaskan kepada anggota regunya/pasukannya manfaat menabung dan membayar uang iuran serta mengajak untuk melakukan gemar menabung",
    "Dapat mengajarkan penggunaan teknologi informasi kepada sedikitnya 2 jenis kepada teman sebaya",
    "Ikut mensosialisasikan cara pengolahan sampah",
    "Dapat mensosialisasikan cara penjernihan air",
    "Dapat membuat pioneering: Jembatan sederhana, Menara pandang sederhana",
    "Dapat membuat peta perjalanan, peta lapangan, menjelaskan rumus menaksir tinggi, lebar, kecepatan dan kedalaman",
    "Dapat menerima dan mengirim berita dengan menggunakan bendera morse dan semaphore serta dapat membuat sandi hasil kreasi pribadi lengkap dengan kuncinya",
    "Selalu berpakaian rapih di setiap saat dan menjadi contoh bagi teman-temannya untuk memelihara kesehatan serta kebersihan diri di lingkungannya",
    "Dapat memimpin dan melatih baris-berbaris di pasukannya",
    "Dapat melaksanakan olahraga beregu dan melakukan 3 jenis cabang olahraga serta tahu peraturannya (Salah satunya olahraga renang)",
    "Dapat mengatasi adanya perubahan perkembangan fisik tubuh",
    "Dapat menjelaskan manfaat dan melakukan aktivitas fisik tiap hari sedikitnya 45 menit"
  ];
}